// packages/react/src/plugins/slot.tsx
import { createSlotRegistry, SlotRegistry, type SlotRegistryOptions } from "@opentui/core/plugins"
import type { CliRenderer, Plugin, PluginContext, PluginErrorEvent } from "@opentui/core"
import React, { Fragment, useEffect, useMemo, useState } from "react"
import type { ReactNode } from "react"

export type SlotMode = "replace" | "append"
type SlotMap = Record<string, object>

export type ReactPlugin<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = Plugin<
  ReactNode,
  TSlots,
  TContext
>

export type ReactSlotProps<TSlots extends SlotMap, K extends keyof TSlots> = {
  name: K
  mode?: SlotMode
  children?: ReactNode
} & TSlots[K]

export type ReactSlotComponent<TSlots extends SlotMap> = <K extends keyof TSlots>(
  props: ReactSlotProps<TSlots, K>,
) => ReactNode

export interface ReactSlotOptions {
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => ReactNode
}

export function createReactSlotRegistry<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  renderer: CliRenderer,
  context: TContext,
  options: SlotRegistryOptions = {},
): SlotRegistry<ReactNode, TSlots, TContext> {
  return createSlotRegistry<ReactNode, TSlots, TContext>(renderer, "react:slot-registry", context, options)
}

function getSlotProps<TSlots extends SlotMap, K extends keyof TSlots>(props: ReactSlotProps<TSlots, K>): TSlots[K] {
  const { children: _children, mode: _mode, name: _name, ...slotProps } = props
  return slotProps as TSlots[K]
}

export function createSlot<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  registry: SlotRegistry<ReactNode, TSlots, TContext>,
  options: ReactSlotOptions = {},
): ReactSlotComponent<TSlots> {
  type PluginErrorBoundaryProps = {
    pluginId: string
    slotName: string
    resetToken: number
    children: ReactNode
  }

  type PluginErrorBoundaryState = {
    failure: PluginErrorEvent | null
  }

  class PluginErrorBoundary extends React.Component<PluginErrorBoundaryProps, PluginErrorBoundaryState> {
    constructor(props: PluginErrorBoundaryProps) {
      super(props)
      this.state = { failure: null }
    }

    override componentDidCatch(error: Error): void {
      const failure = registry.reportPluginError({
        pluginId: this.props.pluginId,
        slot: this.props.slotName,
        phase: "render",
        source: "react",
        error,
      })

      this.setState({ failure })
    }

    override componentDidUpdate(previousProps: PluginErrorBoundaryProps): void {
      if (previousProps.resetToken !== this.props.resetToken && this.state.failure) {
        this.setState({ failure: null })
      }
    }

    override render(): ReactNode {
      if (this.state.failure) {
        return options.pluginFailurePlaceholder ? options.pluginFailurePlaceholder(this.state.failure) : null
      }

      return this.props.children
    }
  }

  return function Slot<K extends keyof TSlots>(props: ReactSlotProps<TSlots, K>): ReactNode {
    const [version, setVersion] = useState(0)

    useEffect(() => {
      return registry.subscribe(() => {
        setVersion((current) => current + 1)
      })
    }, [registry])

    const entries = useMemo(() => registry.resolveEntries(props.name), [registry, props.name, version])
    const slotProps = getSlotProps(props)
    const slotName = String(props.name)

    const renderEntry = (entry: (typeof entries)[number]): ReactNode => {
      const key = `${slotName}:${entry.id}`

      try {
        const rendered = entry.renderer(registry.context, slotProps)
        return (
          <PluginErrorBoundary key={key} pluginId={entry.id} slotName={slotName} resetToken={version}>
            {rendered}
          </PluginErrorBoundary>
        )
      } catch (error) {
        const failure = registry.reportPluginError({
          pluginId: entry.id,
          slot: slotName,
          phase: "render",
          source: "react",
          error,
        })

        if (!options.pluginFailurePlaceholder) {
          return null
        }

        return <Fragment key={key}>{options.pluginFailurePlaceholder(failure)}</Fragment>
      }
    }

    if (entries.length === 0) {
      return <>{props.children}</>
    }

    if (props.mode === "replace") {
      const rendered = renderEntry(entries[0])
      if (rendered === null || rendered === undefined) {
        return <>{props.children}</>
      }

      return <>{rendered}</>
    }

    return (
      <>
        {props.children}
        {entries.map(renderEntry)}
      </>
    )
  }
}

// packages/solid/src/plugins/slot.tsx
import { createSlotRegistry, SlotRegistry, type SlotRegistryOptions } from "@opentui/core/plugins"
import type { CliRenderer, Plugin, PluginContext, PluginErrorEvent } from "@opentui/core"
import { createMemo, createSignal, ErrorBoundary, onCleanup, splitProps, type JSX } from "solid-js"

export type SlotMode = "replace" | "append"
type SlotMap = Record<string, object>

export type SolidPlugin<TSlots extends SlotMap, TContext extends PluginContext = PluginContext> = Plugin<
  JSX.Element,
  TSlots,
  TContext
>

export type SolidSlotProps<TSlots extends SlotMap, K extends keyof TSlots> = {
  name: K
  mode?: SlotMode
  children?: JSX.Element
} & TSlots[K]

export type SolidSlotComponent<TSlots extends SlotMap> = <K extends keyof TSlots>(
  props: SolidSlotProps<TSlots, K>,
) => JSX.Element

export interface SolidSlotOptions {
  pluginFailurePlaceholder?: (failure: PluginErrorEvent) => JSX.Element
}

export function createSolidSlotRegistry<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  renderer: CliRenderer,
  context: TContext,
  options: SlotRegistryOptions = {},
): SlotRegistry<JSX.Element, TSlots, TContext> {
  return createSlotRegistry<JSX.Element, TSlots, TContext>(renderer, "solid:slot-registry", context, options)
}

export function createSlot<TSlots extends SlotMap, TContext extends PluginContext = PluginContext>(
  registry: SlotRegistry<JSX.Element, TSlots, TContext>,
  options: SolidSlotOptions = {},
): SolidSlotComponent<TSlots> {
  return function Slot<K extends keyof TSlots>(props: SolidSlotProps<TSlots, K>): JSX.Element {
    const [local, slotProps] = splitProps(props as SolidSlotProps<TSlots, K>, ["name", "mode", "children"])
    const [version, setVersion] = createSignal(0)

    const unsubscribe = registry.subscribe(() => {
      setVersion((current) => current + 1)
    })
    onCleanup(unsubscribe)

    const entries = createMemo(() => {
      version()
      return registry.resolveEntries(local.name)
    })

    const slotName = () => String(local.name)

    const renderEntry = (
      entry: {
        id: string
        renderer: (ctx: Readonly<TContext>, props: TSlots[K]) => JSX.Element
      },
      fallbackOnError?: JSX.Element,
    ): JSX.Element => {
      const fallbackValue = fallbackOnError ?? (null as unknown as JSX.Element)

      const renderPlugin = (): JSX.Element => {
        try {
          return entry.renderer(registry.context, slotProps as TSlots[K])
        } catch (error) {
          const failure = registry.reportPluginError({
            pluginId: entry.id,
            slot: slotName(),
            phase: "render",
            source: "solid",
            error,
          })

          if (options.pluginFailurePlaceholder) {
            return options.pluginFailurePlaceholder(failure)
          }

          return fallbackValue
        }
      }

      return (
        <ErrorBoundary
          fallback={(error) => {
            const failure = registry.reportPluginError({
              pluginId: entry.id,
              slot: slotName(),
              phase: "render",
              source: "solid",
              error,
            })

            if (options.pluginFailurePlaceholder) {
              return options.pluginFailurePlaceholder(failure)
            }

            return fallbackValue
          }}
        >
          {renderPlugin()}
        </ErrorBoundary>
      )
    }

    return (
      <>
        {(() => {
          const resolvedEntries = entries()

          if (resolvedEntries.length === 0) {
            return local.children
          }

          if (local.mode === "replace") {
            return renderEntry(resolvedEntries[0], local.children as JSX.Element)
          }

          return (
            <>
              {local.children}
              {resolvedEntries.map((entry) => renderEntry(entry))}
            </>
          )
        })()}
      </>
    )
  }
}
